# permissions for end users to view nodelabellers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodelabeller-viewer-role
rules:
- apiGroups:
  - cache.jack-rev.github.com
  resources:
  - nodelabellers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.jack-rev.github.com
  resources:
  - nodelabellers/status
  verbs:
  - get
