# permissions for end users to view nodecleaners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodecleaner-viewer-role
rules:
- apiGroups:
  - cache.jack-rev.github.com
  resources:
  - nodecleaners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.jack-rev.github.com
  resources:
  - nodecleaners/status
  verbs:
  - get
